'use strict';

module.exports = {
	FAVORITE_ADD: 'FAVORITE_ADD',
	FAVORITE_REMOVE: 'FAVORITE_REMOVE',
	INGREDIENTS_ADD: 'INGREDIENTS_ADD',
	INGREDIENTS_REMOVE: 'INGREDIENTS_REMOVE',
	INGREDIENTS_REMOVE_ALL: 'INGREDIENTS_REMOVE_ALL',
}